# this builds dev. Is more or less for staging purposes.
name: Building canary
run-name: Building commit ${{ github.sha }}
on:
  # pull_request:
  #   types: [opened, reopened, synchronize]
  #   paths-ignore:
  #     - '.github/workflows/build.yaml'
  #     - '.github/labels.yml'
  #     - '.github/workflows/labeler.yaml'
  workflow_dispatch:
  push:
    branches:
      #- master
      - dev

jobs:
  build-image:
    if: ${{ github.event.label.name != 'sync' }}
    runs-on: ubuntu-latest
    environment: 
      name: canary
      url: https://feedbackai-tool-canary-backend.iswleuven.be/
    # permissions:
    #   packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: setup params
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "BRANCH=${GITHUB_HEAD_REF}" | tr / - >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.REPO }}:canary
            ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
